[plugin]
id = "steam_hoverless"
name = "Steam Hoverless"
version = "1.0.0"
author = "SnipCheddaBombs"
description = "Disables Steam game hover preview popups in Store/Home and Library."

[frontend]
entry = "frontend/index.tsx"


[compiler]
output_path = "auto"

[webkit]
entry = "webview/preload.ts"
